  apiVersion: portworx.io/v1beta2
  kind: VolumePlacementStrategy
  metadata:
    name: kafka-volume-affinity
    namespace: kz
  spec:
    volumeAffinity:
    - matchExpressions:
      - key: storage
        operator: In
        values:
          - kafka
---
  apiVersion: portworx.io/v1beta2
  kind: VolumePlacementStrategy
  metadata:
    name: zookeeper-volume-affinity
    namespace: kz
  spec:
    volumeAffinity:
    - matchExpressions:
      - key: storage
        operator: In
        values:
          - zookeeper
---
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: px-kafka
  namespace: kz
provisioner: kubernetes.io/portworx-volume
parameters:
  repl: "2"
  io_profile: "sequential"
  priority_io: "high"
  placement_strategy: "kafka"
---
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: px-zookeeper
  namespace: kz
provisioner: kubernetes.io/portworx-volume
parameters:
  repl: "q"
  io_profile: "sequential"
  priority_io: "high"
  placement_strategy: "zookeeper"

