kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: px-jenkins-sc
provisioner: kubernetes.io/portworx-volume
parameters:
  repl: "2"
  shared: "true"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
   name: jenkins-data
   annotations:
     volume.beta.kubernetes.io/storage-class: px-jenkins-sc
spec:
   accessModes:
     - ReadWriteOnce
   resources:
     requests:
       storage: 6Gi