kind: Service
apiVersion: v1
metadata:
  name: petclinic
  labels:
    app: petclinic
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    nodePort: 32323
    targetPort: 8080
  selector:
    app: petclinic
---
kind: Service
apiVersion: v1
metadata:
  name: petclinic
  labels:
    app: petclinic
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: petclinic
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: petclinic
  labels:
    app: petclinic
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      containers:
      - name: petclinic
        image: springdeveloper/spring-petclinic:2.0.0.BUILD-SNAPSHOT
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /manage/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /manage/health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 5
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: 'production,kubernetes'
        - name: MYSQL_HOST
          value: petclinic-db-mysql
        - name: MYSQL_USERNAME
          value: root
        - name: MYSQL_PASSWORD
          value: superpassword